# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/normalized_ta',
                'doc_host': 'https://Tianxu-Jia.github.io',
                'git_url': 'https://github.com/Tianxu-Jia/normalized_ta',
                'lib_path': 'normalized_ta'},
  'syms': {'normalized_ta.core': {'normalized_ta.core.foo': ('core.html#foo', 'normalized_ta/core.py')}}}
